### ISSUE TITLE
Migration to version 16.0

### ISSUE THREAD

**Issue by sbidoul** [OCA/helpdesk#370]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0

# Modules to migrate

- [x] helpdesk_mgmt - By @zuher83 - #440
- [x] helpdesk_mgmt_project - By @zuher83 - #441
- [x] helpdesk_mgmt_rating - By @carolinafernandez-tecnativa - #554
- [x] helpdesk_mgmt_sale - By @victoralmau - #806
- [ ] helpdesk_mgmt_sla - By @AntoniRomera - #450
- [x] helpdesk_mgmt_timesheet - By @AntoniRomera - #483
- [x] helpdesk_motive - By @adasatorres - #526
- [x] helpdesk_type - By @Boxnia - #470

Missing module? Check https://github.com/OCA/maintainer-tools/wiki/%5BFAQ%5D-Missing-modules-in-migration-issue-list

**Comment by Entrepreneur-AJ** [comment]
base module ready for review: https://github.com/OCA/helpdesk/pull/407

**Comment by pausanchezqubiq** [comment]
working on helpdesk_type

**Comment by jasonribble** [comment]
@pausanchezqubiq how's it coming along? Do you need any assistance?

**Comment by abhinavvaidya-tsd** [comment]
@pedrobaeza Is anyone working on the "helpdesk_mgmt_sla". There is no activity since April 2023 ? If not I can work on it

**Comment by pedrobaeza** [comment]
It seems there's none asking for it, so you can go on.
